[package]
name = "vkxml"
version = "0.2.0"
authors = ["Terry Brashaw <terrybrashaw@gmail.com>"]

[dependencies]
serde = "*"
serde_derive = "*"
serde-xml-rs = {path = "https://github.com/RReverser/serde-xml-rs.git"}
